[package]
name = "virgil"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
log = "*"
env_logger = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"
image = "*"
pico-args = "*"
lang-c = "*"
sdl2 = {version = "*", features = ["image"]}